apiVersion: v2
name: myapp
description: A Helm chart for deploying Flask application to Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - flask
  - demo
  - cloudbuild
maintainers:
  - name: DevOps Team
    email: devops@example.com
